export const en = {
  APP_TITLE: "RealTime Chat App",

  // page constants
  CONFIRM_LEAVE_PAGE_TITLE: "Leave this page?",
  CONFIRM_LEAVE_PAGE_MESSAGE: "Do you want to leave this page?",
  CONFIRM_SIGN_OUT_TITLE: "Logout of Chat app?",
  CONFIRM_SIGN_OUT_MESSAGE: "Are you sure you want to logout?",
  // firestore
  DB_ROOM_COLLECTION: "rooms",
  DB_CHAT_COLLECTION: "chats",
  DB_ORDER_BY_CREATED_DATE: "date_created",
  ASC_ORDER: "asc",
  DESC_ORDER: "desc",
  // firestore collenction or document names
  ROOMS: "rooms",
  USERNAME: "username",
  USERNAMES: "usernames",
  DATE_CREATED: "date_created",
  // socket.io
  SOCKET_JOIN: "join",
  SOCKET_MESSAGE: "message",
  SOCKET_ROOM_DATA: "roomData",
  SOCKET_DISSCONNECTED: "disconnected",
  SOCKET_SEND_MESSAGE: "sendMessage",
  // Error messagess
  NO_RESULT: "No Result",
  FETCH_USER_ERROR: "Fetch User Error",
  FETCH_USER_ERROR_NO_EMAIL: "Fetch User Error: No email address is set",
  FETCH_DATA_ERROR: "There's something wrong with fetching data",
  ROOM_ALREADY_EXISTS_ERROR: "Room name is already taken",
  ROOM_NOT_EXISTS_ERROR: "Room does not exists",
  ROOM_NAME_ALREADY_EXISTS_ERROR: "This room name is already taken",
  CREATE_ROOM_ERROR: "Creatting Room Error",
  UPDATE_MESSAGE_ERROR: "Update Message Error",
  FETCH_MESSAGE_ERROR: "FetchMessageError",
  JOIN_ROOM_ERROR:
    "Something wrong happen with the system while joinning the room",
  USERNAME_EXISTS_ERROR: "This user name is taken",
  UNDEFINED_ERROR: "Undefined error",
  RETRIEVE_USERNAME_ERROR: "There's probrem with retrieving username",
  USER_NOT_FOUND_IN_CHAT:
    "Your username were not found in the chat room, please re-join this room again.",
  REQUIRE_ROOM_NAME_ERROR: "Room name is required.",
  NO_EMAIL_OR_PASSWORD_SYSERROR:
    "System error. Email or password are null or undefined",
  // Page labels
  SIGN_IN: "Sign In",
  SIGN_UP: "Sign Up",
  LOG_IN: "Log In",
  LOG_OUT: "Log out",
  SEND: "Send",
  USERNAME_PLACEHOLDER: "User Name",
  EMAIL_PLACEHOLDER: "Email Address",
  PASSWORD_PLACEHOLDER: "Password",
  SIGN_IN_LINK: "Click here to sign in.",
  SIGN_UP_LINK: "Click here to sign up.",
  LAUNCH_ROOM_TITLE: "Launch Room",
  LAUNCH_ROOM_BUTTON_TITLE: "Launch Room",
  LAUNCH_ROOM_LINK_TITLE: "Already have a room?",
  JOIN_TITLE: "Join",
  JOIN_ROOM_TITLE: "Join Room",
  JOIN_ROOM_BUTTON_TITLE: "Join Room",
  JOIN_ROOM_LINK_TITLE: "If you don't have a room yet, create it here.",
  ROOM_USERNAME_PLACEHOLDER: "Name",
  ROOMNAME_PLACEHOLDER: "Room Name",
  FIND_ROOMS: "Find Room",
  CLOSE: "Close",
  LOAD_MORE: "Load More",
  CURR_CHATTING_USERS: "People currently chatting: ",
};
